gitlab:
  api_url: "https://company.gitlab.com/api/v4"
  token: "<GITLAB_TOKEN>"
  mirror:
    url: "https://gitlab.com/api/v4"
    group_id: "<GITLAB_MIRROR_GROUP_ID>"
    group_path: "gitlab.com/<GROUP_NAME>"  
    username: "<GITLAB_MIRROR_USERNAME>"
    token: "<GITLAB_MIRROR_TOKEN>"
postmark:
  api_url: "https://api.postmarkapp.com"
  token: <POSTMARK_TOKEN>
  slack_webhook: "<POSTMARK_SLACK_WEBHOOK>"
onepassword:
  address: "<ONEPASSWORD_ADDRESS>"