#!/usr/bin/env bash
# Generates the Homebrew formulas of opsi from the output of GoReleaser.
#
# Usage: scripts/homebrew-formula.sh <dist-dir> <output-dir>
#
# Writes <output-dir>/opsi.rb and <output-dir>/opsi@<version>.rb, reading the
# release version and the archives (name, platform, checksum) from
# <dist-dir>/metadata.json and <dist-dir>/artifacts.json.
set -euo pipefail

dist="${1:?usage: $0 <dist-dir> <output-dir>}"
out="${2:?usage: $0 <dist-dir> <output-dir>}"

repo="beliven-it/opsi"
desc="All-in-one CLI for Beliven Ops daily usage!"

version="$(jq -r '.version' "$dist/metadata.json")"
tag="$(jq -r '.tag' "$dist/metadata.json")"

# archive <os> <arch> prints "<url> <sha256>" for the matching archive.
archive() {
  jq -er --arg os "$1" --arg arch "$2" --arg repo "$repo" --arg tag "$tag" '
    [.[] | select(.type == "Archive" and .goos == $os and .goarch == $arch)][0]
    | "https://github.com/\($repo)/releases/download/\($tag)/\(.name) \(.extra.Checksum | sub("^sha256:"; ""))"
  ' "$dist/artifacts.json"
}

# class_name <formula> follows the Homebrew convention: opsi@1.2.3 -> OpsiAT123.
class_name() {
  local name="${1//@/-AT-}" part result=""
  name="${name//./}"
  IFS='-_' read -ra parts <<<"$name"
  for part in "${parts[@]}"; do
    [ -z "$part" ] && continue
    part="$(tr '[:upper:]' '[:lower:]' <<<"$part")"
    result+="$(tr '[:lower:]' '[:upper:]' <<<"${part:0:1}")${part:1}"
  done
  echo "${result/At/AT}"
}

# platform <condition> <os> <arch> <blank-line-before-install: yes|no>
platform() {
  local condition="$1" os="$2" arch="$3" blank="$4" url sha
  read -r url sha <<<"$(archive "$os" "$arch")"
  printf '    if %s\n' "$condition"
  printf '      url "%s"\n' "$url"
  printf '      sha256 "%s"\n' "$sha"
  [ "$blank" = "yes" ] && printf '\n'
  printf '      define_method(:install) do\n'
  printf '        bin.install "opsi"\n'
  printf '      end\n'
  printf '    end\n'
}

formula() {
  local class="$1"
  cat <<RUBY
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ${class} < Formula
  desc "${desc}"
  homepage ""
  version "${version}"
  license "MIT"

  on_macos do
$(platform "Hardware::CPU.intel?" darwin amd64 yes)
$(platform "Hardware::CPU.arm?" darwin arm64 yes)
  end

  on_linux do
$(platform "Hardware::CPU.intel? && Hardware::CPU.is_64_bit?" linux amd64 no)
$(platform "Hardware::CPU.arm? && Hardware::CPU.is_64_bit?" linux arm64 no)
  end

  def caveats
    <<~EOS
      Run \`opsi init\` to generate config file inside
       \`~/.config/opsi/config.yml\` (works only if not exists yet).

       Type \`opsi help\` for further information.
    EOS
  end
end
RUBY
}

mkdir -p "$out"
formula "$(class_name opsi)" >"$out/opsi.rb"
formula "$(class_name "opsi@${version}")" >"$out/opsi@${version}.rb"
