#!/usr/bin/env bash
# Publishes the Homebrew formulas generated by scripts/homebrew-formula.sh to
# the tap.
#
# Usage: scripts/homebrew-publish.sh <formulas-dir> <tap-repository> <version>
#
# Copies the *.rb files of <formulas-dir> into Formula/ of <tap-repository> (any
# URL or path git can clone) and pushes the commit to its default branch.
# Nothing is pushed when the tap already has the same formulas.
set -euo pipefail

formulas="${1:?usage: $0 <formulas-dir> <tap-repository> <version>}"
tap="${2:?usage: $0 <formulas-dir> <tap-repository> <version>}"
version="${3:?usage: $0 <formulas-dir> <tap-repository> <version>}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

git clone --quiet "$tap" "$work"
mkdir -p "$work/Formula"
cp "$formulas"/*.rb "$work/Formula/"

cd "$work"
git add Formula
if git diff --cached --quiet; then
  echo "The tap already has the formulas of opsi $version"
  exit 0
fi

git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
  commit --quiet -m "Brew formula update for opsi version $version"
git push --quiet origin HEAD
echo "Published the formulas of opsi $version"
